markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'

baseurl: /

# Website info
title: 본헤어
display_title: BONHAIR
description: 본헤어는 고객님 한분 한분의 마음까지 디자인하는 미용실입니다.
keywords: 본헤어, BONHAIR, 천안 본헤어, 천안 미용실, 천안 머리, 천안 헤어, 신부동 본헤어, 신부동 미용실, 신부동 머리, 신부동 헤어, 미용실, 머리, 헤어, 본헤어 천안 터미널사거리 근처 헤어샵, 컷, 펌, 염색, 매직, 클리닉
display_description: 정직한 마음으로, 기본을 지키고 가치를 창출합니다.
cover: False #assets/images/bonhair/min-ji.jpge
logo: False # 로고 이미지 : assets/images/blog-icon.png
logo_dark: False # 로고 이미지 : assets/images/favicon.png
favicon: # 탭 이미지 : assets/images/favicon.png
production_url: http://www.bonhair.co.kr/
source_url: https://github.com/bonhair/homepage/

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: False
facebook: bonhair151220

# Disqus
disqus: False
disqus_shortname: bonhair # replace with your disqus username

# Google Analytics
google_analytics: UA-117588004-1

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: bonhair
repo: homepage
branch: master
relative_source: ../homepage/
destination: ../homepage-pages/
production_url: http://www.bonhair.co.kr/
source_url:  https://github.com/bonhair/homepage/

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*